CREATE TABLE `yahoo_options` (
   `data_id` bigint(20) NOT NULL AUTO_INCREMENT,
   `stock` varchar(10) DEFAULT NULL,
   `contractSymbol` varchar(30) NOT NULL,
   `strike` double DEFAULT NULL,
   `currency` varchar(10) DEFAULT NULL,
   `lastPrice` double DEFAULT NULL,
   `priceChange` double DEFAULT NULL,
   `percentChange` double DEFAULT NULL,
   `volume` double DEFAULT NULL,
   `openInterest` double DEFAULT NULL,
   `bid` double DEFAULT NULL,
   `ask` double DEFAULT NULL,
   `contractSize` varchar(20) DEFAULT NULL,
   `expirationUnix` bigint(20) DEFAULT NULL,
   `lastTradeDate` date DEFAULT NULL,
   `impliedVolatility` double DEFAULT NULL,
   `inTheMoney` tinyint(4) DEFAULT NULL,
   `expirationDate` date DEFAULT NULL,
   `optionType` varchar(10) DEFAULT NULL,
   `updated_dt` date NOT NULL,
   PRIMARY KEY (`data_id`,`updated_dt`,`contractSymbol`),
   UNIQUE KEY `unique` (`contractSymbol`,`updated_dt`),
   KEY `idx_yahoo_options_stock` (`stock`),
   KEY `idx_yahoo_options_optionType` (`optionType`),
   KEY `idx_yahoo_options_inTheMoney` (`inTheMoney`),
   KEY `idx_yahoo_options_expirationDate` (`expirationDate`),
   KEY `idx_yahoo_options_expirationUnix` (`expirationUnix`),
   KEY `idx_yahoo_options_strike` (`strike`)
 ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8